crmProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls', namespace='product')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('user.urls', namespace='user')),
]

customer/urls.py
from django.urls import path
from customer.views import customer_list, updateCustomer, deleteCustomer, accountsetting
from django.conf.urls.static import static
from django.conf import settings

app_name='customer'
urlpatterns=[
    path('customer-list/<str:pk>/', customer_list, name='customers_list'),
    path('update-customer/<int:id>', updateCustomer, name='update_customer'),
    path('delete-customer/<int:id>', deleteCustomer, name='delete_customer'),
    path('account/', accountsetting, name='account'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product.views import productList, createOrder, updateOrder, deleteOrder, search

app_name='product'

urlpatterns=[ 
    path('product-list/', productList, name='product_list'),
    path('create-order/<int:id>', createOrder, name='create_order'),
    path('update-order/<int:id>',updateOrder, name='update_order'),
    path('delete-order/<int:id>', deleteOrder, name='delete_order'),
    path('search/', search, name='search'),
    
]

user/urls.py
from django.urls import path
from user.views import dashboard, login_view, register_view, logout_view, user_view
app_name='user'

urlpatterns=[ 
    path('', dashboard, name='dashboard'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/',logout_view, name='logout'),
    path('user/',user_view, name='user_view'),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    email=forms.EmailField(max_length=200, )
    class Meta:
        model=User
        fields=['username', 'email', 'password1','password2']

user/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from customer.models import Customer
from product.models import Order
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from user.forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from user.decorators import unauthenticated, admin_only, allowed_users
from django.contrib.auth.models import Group
# Create your views here.
# @allowed_users(allowed_roles=['admin'])
@login_required(login_url='user:login')
# @admin_only
def dashboard(request):
    customers=Customer.objects.all()
    orders=Order.objects.all()
    total_order=Order.objects.all().count()
    delivered=orders.filter(status='Delivery').count()
    pending=orders.filter(status='Pending').count()

    context={'customers':customers, 'orders':orders,
    'total_order':total_order,
    'delivered':delivered,
    'pending':pending,
    'title':'Dashboard'
    }
    return render(request,'dashboard.html', context)


@unauthenticated
def login_view(request):
    form=AuthenticationForm(request.POST or None)
    if request.POST:
        username=request.POST.get('username')
        password=request.POST.get("password")
        user=authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.is_superuser:
                return HttpResponseRedirect(reverse('user:dashboard'))
            else:
                return HttpResponseRedirect(reverse('user:user_view'))
        else:
            messages.info(request, 'Username or Password is Incorrect')
    context={'form':form}
    return render(request, 'login.html', context)


@unauthenticated
def register_view(request):
    form=CreateUserForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            user=form.save()
            username=form.cleaned_data.get('username')
            group=Group.objects.get(name='customer')
            user.groups.add(group)
            # Customer.objects.create(user=user)
            messages.success(request, "Account has been created for "+username)
            return HttpResponseRedirect(reverse('user:login'))
    context={'form':form}
    return render(request, 'register.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:login'))

@login_required(login_url='user:login')
@allowed_users(allowed_roles=['customer'])
def user_view(request):
    orders=request.user.customer.order_set.all()
    total_order=orders.count()
    delivered=orders.filter(status='Delivery').count()
    pending=orders.filter(status='Pending').count()

    print("Orders", orders)
    context={"orders":orders,
    'total_order':total_order,
    'delivered':delivered,
    'pending':pending,
    }
    return render(request,'user.html', context)

user/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

{% include 'components/status.html' %}
<div class="row">
    <div class="col-md-5">
        <h5>CUSTOMERS</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-primary btn-sm btn-block" href="#">Create Customer</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Customer</th>
                    <th>Phone</th>

                    {% for customer in customers %}
                        <tr>
                            <td><a class="btn btn-sm btn-info" href="{% url 'customer:customers_list' customer.id %}">View</a></td>
                            <td>{{customer.firstname}}</td>
                            <td>{{customer.phone}}</td>
                        </tr>
                    {% endfor %}
                </tr>
            </table>
        </div>

    </div>
    <div class="col-md-7">
        <h5>LAST 5 ORDERS</h5>
        <hr>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Order</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>
                
                {% for order in orders %}
                <tr>
                    <td>{{order.product}}</td>
                    <td>{{order.date_created}}</td>
                    <td>{{order.status}}</td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'product:update_order' order.id %}">Update</a></td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'product:delete_order' order.id %}">Remove</a></td>
                </tr>
            {% endfor %}
            </table>
        </div>

    </div>
</div>
    <hr>
{% endblock content %}

user/templates/login.html
{% load static %}
<!-- <h1>Login</h1>
<form method="post", action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit", name="Submit", value="Log In">
</form> -->


<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
    crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" 
    integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" 
    crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/login.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
                        
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				
				{% for message in messages %}
					{{message}}
				{% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'user:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

user/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>  
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/register.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
				{{form.errors}}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'user:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

<!-- <form method="post" action="#">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Sign Up" name="Submit">
</form> -->

user/templates/user.html
{% extends 'base.html' %}
{% block content %}
    {% include 'components/status.html' %}
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <table class="table table-sm">
                    <tr>
                        <th>Product</th>
                        <th>Category</th>
                        <th>Date Orderd</th>
                        <th>Status</th>
                    </tr>
                    {% for order in orders %}
                        <tr>
                            <td>{{order.product}}</td>
                            <td>{{order.product.category}}</td>
                            <td>{{order.date_created}}</td>
                            <td>{{order.status}}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    
{% endblock %}