crmProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls', namespace='product')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('user.urls', namespace='user')),
]

customer/urls.py
from django.urls import path
from customer.views import customer_list, updateCustomer, deleteCustomer, accountsetting
from django.conf.urls.static import static
from django.conf import settings

app_name='customer'
urlpatterns=[
    path('customer-list/<str:pk>/', customer_list, name='customers_list'),
    path('update-customer/<int:id>', updateCustomer, name='update_customer'),
    path('delete-customer/<int:id>', deleteCustomer, name='delete_customer'),
    path('account/', accountsetting, name='account'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product.views import productList, createOrder, updateOrder, deleteOrder, search

app_name='product'

urlpatterns=[ 
    path('product-list/', productList, name='product_list'),
    path('create-order/<int:id>', createOrder, name='create_order'),
    path('update-order/<int:id>',updateOrder, name='update_order'),
    path('delete-order/<int:id>', deleteOrder, name='delete_order'),
    path('search/', search, name='search'),
    
]

user/urls.py
from django.urls import path
from user.views import dashboard, login_view, register_view, logout_view, user_view
app_name='user'

urlpatterns=[ 
    path('', dashboard, name='dashboard'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/',logout_view, name='logout'),
    path('user/',user_view, name='user_view'),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user=models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100, null=True)
    lastname= models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=20, null=True)
    address=models.CharField(max_length=150, blank=True, null=True)
    avtar=models.ImageField(upload_to='profile/', null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return str(self.firstname)
        

customer/forms.py
from django import forms
from customer.models import Customer

class CustomerForm(forms.ModelForm):
    class Meta():
        model = Customer
        fields = '__all__'
        exclude=['user',]

customer/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from customer.models import Customer
from product.models import Order
from customer.forms import CustomerForm
from customer.filters import OrderFilter
from django.contrib.auth.decorators import login_required
from user.decorators import allowed_users
# Create your views here.
@login_required(login_url='user:login')
def customer_list(request, pk):
    customer=Customer.objects.get(id=pk)
    orders=customer.order_set.all()
    order_count=orders.count()

    myFilter=OrderFilter(request.GET, queryset=orders)
    orders=myFilter.qs

    context={'customer':customer,
    'orders':orders,
    'orders_count':order_count,
    'myFilter':myFilter,
    'title':'Customer'}
    return render(request, 'customers.html', context)

def updateCustomer(request, id):
    customer=get_object_or_404(Customer, id=id)
    # form=CustomerForm(request.POST or None, instance=customer)
    # if request.POST:
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect(reverse('user:dashboard'))
    context={"customer":customer}
    return render(request,'customers.html', context)

def deleteCustomer(request,id):
    return render(request, 'customers.html')


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['customer'])
def accountsetting(request):
    user=request.user.customer
    form=CustomerForm(request.POST or None, request.FILES or None, instance=user)
    if request.POST:
        if form.is_valid:
            form.save
    context={'form':form}
    return render(request,'account_setting.html', context)

customer/templates/account_setting.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>
<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
            <a class="btn btn-warning" href="{% url 'user:user_view' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.avtar.url}}" >
		
        </div>
    </div>
    <div class="col-md-9">
        <div class="card card-body">
            <form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
		
			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
        </div>

    </div>
</div>
<!-- {{request.user.customer.profile_pic.url}} -->






{% endblock content %}

customer/templates/customers.html
{% extends 'base.html' %}

{% block content %}

<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'customer:update_customer' customer.id %}">Update Customer</a>
			<br>
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'product:create_order' customer.id %}">Create Orders</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Email: {{customer.email}}</p>
			<p>Phone: {{customer.phone}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{orders_count}}</h1>
		</div>
	</div>
</div>


<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">
				{{myFilter.form}}

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
	
</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
				{% for order in orders %}
					<tr>
						<td>{{order.product}}</td>
						<td>{{order.product.category}}</td>
						<td>{{order.date_created}}</td>
						<td>{{order.status}}</td>
						<td><a class="btn btn-sm btn-info" href="{% url 'product:update_order' order.id %}">Update</a></td>
                    	<td><a class="btn btn-sm btn-danger" href="{% url 'product:delete_order' order.id %}">Remove</a></td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>

{% endblock content%}