crmProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls', namespace='product')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('', include('user.urls', namespace='user')),
]

customer/urls.py
from django.urls import path
from customer.views import customer_list, updateCustomer, deleteCustomer, accountsetting
from django.conf.urls.static import static
from django.conf import settings

app_name='customer'
urlpatterns=[
    path('customer-list/<str:pk>/', customer_list, name='customers_list'),
    path('update-customer/<int:id>', updateCustomer, name='update_customer'),
    path('delete-customer/<int:id>', deleteCustomer, name='delete_customer'),
    path('account/', accountsetting, name='account'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product.views import productList, createOrder, updateOrder, deleteOrder, search

app_name='product'

urlpatterns=[ 
    path('product-list/', productList, name='product_list'),
    path('create-order/<int:id>', createOrder, name='create_order'),
    path('update-order/<int:id>',updateOrder, name='update_order'),
    path('delete-order/<int:id>', deleteOrder, name='delete_order'),
    path('search/', search, name='search'),
    
]

user/urls.py
from django.urls import path
from user.views import dashboard, login_view, register_view, logout_view, user_view
app_name='user'

urlpatterns=[ 
    path('', dashboard, name='dashboard'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/',logout_view, name='logout'),
    path('user/',user_view, name='user_view'),
]

templates/components/navbar.html
<style>
  .hello-msg{
    font-size: 18px;
    text-transform: capitalize;
    color: #fff;
    margin-right: 10px;
  }
  a{
    text-decoration: none;
  }
  
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">CRM Project</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'user:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'product:product_list' %}">Product</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'customer:account' %}">Settings</a>
          </li>
          {% endif %}
          
        </ul>

        <!-- <form class="d-flex" method="post" action="{% url 'product:search' %}">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
        <span class="hello-msg">Hello , {{request.user}}</span>
        <span><a class="hello-msg" href="{% url 'user:logout' %}">Log Out</a></span>
      </div>
    </div>
</nav>

templates/components/status.html
{% load static %}
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ total_order }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ delivered }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ pending }}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>